#!/usr/bin/env -S ansible-playbook -i localhost, -t noop --vault-password-file secrets.pwd
---
- name: Setup Projects
  hosts: "{{ target_hosts | default('localhost') }}"
  connection: "{{ target_connection | default('local') }}"
  become: yes
  become_user: "{{ target_user | default(lookup('env', 'USER')) }}"
  vars_files:
    - secrets.enc
  vars:
    ansible_pipelining: true
    allow_world_readable_tmpfiles: true
  
    para_path: "{{ ansible_user_dir }}/para"
    para_areas_path: "{{ para_path }}/professional/areas"
    content_directories:
      - "{{ ansible_user_dir }}/.aws"
      - "{{ ansible_user_dir }}/.ssh"
      - "{{ ansible_user_dir }}/.local/share/python"
      - "{{ ansible_user_dir }}/.config/zsh-ext"
    repositories:
      - repo: git@github.com:maxcole/rws-bootstrap.git
        dest: "{{ para_areas_path }}/rws/bootstrap"
      - repo: git@github.com:maxcole/rws-infra.git
        dest: "{{ para_areas_path }}/rws/infra"
      - repo: git@github.com:maxcole/rws-utils.git
        dest: "{{ para_areas_path }}/rws/utils"
    stow:
      - src: "{{ playbook_dir }}"
        dest: "{{ ansible_user_dir }}"
        packages: [dotfiles]
    secrets:
      - file: "{{ playbook_dir }}/secrets.enc"
        var: "{{ _secrets }}"
  
  tasks:
    - include_role:
        name: rjayroach.common.content
      tags: [debug, user-install]
