#!/usr/bin/env -S ansible-playbook -i localhost,
---
- name: Setup Projects
  hosts: "{{ target_hosts | default('localhost') }}"
  connection: "{{ target_connection | default('local') }}"
  become: yes
  become_user: "{{ target_user | default(lookup('env', 'USER')) }}"
  vars_files:
    - secrets.enc
  vars:
    ansible_pipelining: true
    allow_world_readable_tmpfiles: true
  
  vars:
    para_path: "{{ ansible_user_dir }}/para"
    para_areas_path: "{{ para_path }}/professional/areas"
    # content_directories:
    #   - "{{ ansible_user_dir }}/.config/tmuxinator"
    repositories:
      - repo: git@github.com:maxcole/provider-infra.git
        dest: "{{ para_areas_path }}/home-lab/provider/infra"
      - repo: git@github.com:maxcole/bootstrap.git
        dest: "{{ para_areas_path }}/home-lab/provider/bootstrap"
      - repo: git@github.com:maxcole/config.git
        dest: "{{ para_areas_path }}/config"
      - repo: git@github.com:maxcole/packer.git
        dest: "{{ para_areas_path }}/packer"
    stow:
      - src: "{{ playbook_dir }}"
        dest: "{{ ansible_user_dir }}"
        packages: [dotfiles]
  
  tasks:
    - include_role:
        name: rjayroach.common.content
      tags: [user-install]

    - ansible.builtin.debug:
        var: "{{ item }}"
      loop: [ansible_env, ansible_user_id, ansible_user_dir]
      tags: [debug, never]

    - name: "Create dirs in {{ ansible_user_dir }}"
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/{{ item }}"
        state: directory
        mode: '0755'
      loop: [.aws, .ssh, .local, .local/share, .local/share/python, .local/bin]

      # NOTE: This is the last thing to do
    - name: Create credentials for encrypted values
      ansible.builtin.copy:
        dest: "{{ item.dest }}"
        content: |
          # DO NOT EDIT; This file was generated by Ansible from {{ playbook_dir }}/secrets.enc
          {% for k, v in item.content.items() %}
          {{ k }}{% if v is not none %}={{ v }}{% endif %}

          {% endfor %}
      loop: "{{ _secrets }}"
